// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'package:optombai/firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlsTcPWc_n4W5hirj2KIah9I7L4JbVg7M',
    appId: '1:291812609091:web:73fb9d9e13fd00282958f6',
    messagingSenderId: '291812609091',
    projectId: 'elba-d9541',
    authDomain: 'elba-d9541.firebaseapp.com',
    databaseURL: 'https://elba-d9541-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'elba-d9541.firebasestorage.app',
    measurementId: 'G-MK16J10J8Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBN3bRlOJOm_CFaYa5cVKT0Qlug3cWOaKs',
    appId: '1:291812609091:android:6c9f69493455ccc42958f6',
    messagingSenderId: '291812609091',
    projectId: 'elba-d9541',
    databaseURL: 'https://elba-d9541-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'elba-d9541.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaGHxDwuPCBXqMGTHDEsmzmPXCtTmh1c0',
    appId: '1:291812609091:ios:7ec8793d10c411a52958f6',
    messagingSenderId: '291812609091',
    projectId: 'elba-d9541',
    databaseURL: 'https://elba-d9541-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'elba-d9541.firebasestorage.app',
    iosBundleId: 'kg.eilbay.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaGHxDwuPCBXqMGTHDEsmzmPXCtTmh1c0',
    appId: '1:291812609091:ios:daf066b19f9127082958f6',
    messagingSenderId: '291812609091',
    projectId: 'elba-d9541',
    databaseURL: 'https://elba-d9541-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'elba-d9541.firebasestorage.app',
    iosBundleId: 'com.example.eilbay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlsTcPWc_n4W5hirj2KIah9I7L4JbVg7M',
    appId: '1:291812609091:web:3afa4162a06a7c3b2958f6',
    messagingSenderId: '291812609091',
    projectId: 'elba-d9541',
    authDomain: 'elba-d9541.firebaseapp.com',
    databaseURL: 'https://elba-d9541-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'elba-d9541.firebasestorage.app',
    measurementId: 'G-WB0DELC9XM',
  );
}